# Auditable plausibility score for 'Local Validity and Contextual Holonomy' (Feb 2026 note).
# Rerun after each iteration; evidence column cites suite scripts. Judgment made explicit.
ROWS = [
 # (component, weight, as_written, current, evidence / what moves it next)
 ("S2 local classicality (MASA/Spec)",        15, 13, 15, "V23+V46: every context trivializable; SHARP valuation mu_d (even d) / mu_{2d} (odd d, sharp at d=3) via parity lemma + Ext transgression; even-d half-step-necessity RETRACTED (layout artifact, see V44/V46); global contrast V10/V13/V33"),
 ("S3 groupoid + cocycle core",               35,  8, 35, "as-written: wrong groupoid (PaperA Thm1) + "
   "'encodes' false in strong form (V13,V25). patched: PU(n) fix + Thm Q/J weak claim, V10-V13. "
   "V24 DONE: unsolvability<=>odd-cycle, 2100 random families + pinned PM/cert4, 0 mismatches. V36 CORRECTED: d=4 tier-2 exact facet ARITHMETIC pinned (rank-32, |c|=3/(2sqrt2), bounds {6,7}); completeness retracted after fresh-sample audit (construction-sample 40/40 was partially circular); tier-2 exact facets (V53 CORRECTION: all facet functionals RATIONAL; the 4*sqrt2 & 14*sqrt2/3 unit bounds were a normalization artifact - exact {0,+-1} lifts with integer bounds {6,7}; quadratic fields enter only via norms).remaining: orbit enumeration, NS formula, mixed families. V34: GHOST LAW PROVED (identity + parity sub-lemma verified x6 deletions); TAU-NECESSITY: 12 rigorous certificates that the d=4 state sector is invisible at the order-2 layer. COMPLETION LEMMA proved (d=2 theorem closed). V33 TOWER GHOST LAW: offset gamma-s* = d/2 at d=4 (both ghost types), eigenstate CF=1 saturation; Hermitian-shadow formula refuted at d=4 (0.138 counterexamples). V32 GHOST FACET THM + FORMULA: CF=max(0,(S*-1)/2), two-tetrahedra mechanism, Bell CF=1 corollary; proofs written except completion lemma. V31 THEOREM: CF=0 <=> c in conv(L(F)) (codeword polytope; 24 triangle facets; 40/40 x2; unifies AvN via L=empty). V29/V30: global frames eliminated in both directions (Lemma no-net, PM certificate; GHW rand16/TxT certs) - scenario-paired classifier is FORCED"),
 ("S4 collapse / Lueders",                    25, 15, 22, "S4 (V40 + written treatment): Thm A sharp core ((i)+(ii) => orthogonal 1-eigenspaces), Thm B = V37 on the core, Thm C classical twin. V37: +repeatability+commutant-covariance => the 1-param AFFINE depolarizing line per degenerate block; efficiency <=> Lueders (unique single-Kraus). "
   "CORRECTION 2026-07-11 (second external audit; row 25->22): (a) V37 CP range was WRONG ([0,1] -> exact -1/(r^2-1)<=p<=1, affine not convex; lueders_cp_interval.py); (b) V37 relabeled numerical stress test, not 'machine-exact'; (c) V40's pinned qubit counterexample diag(1,c) was INVALID (outcome 2 not repeatable; only outcome 1 was checked) -> replaced by a valid qutrit example, every outcome checked; (d) classical range [0,1] -> -1/(m-1)<=t<=1, with the m=2 swap a second deterministic member. Core claim (Lueders unique single-Kraus member) survives. next: instrument-level generality, exact (symbolic) certification"),
 ("operational consistency (no new preds)",   10, 10, 10, "by construction"),
 ("Copenhagen adequacy (observer/WF)",         15,  6, 12, "PAPER D: Thm4 FR LOCALIZED (V39: trivial class + hol=+1 invariant; state-sector CF=1/6 exact, facet=CHSH 7/3, ABM match); Thm1 relative facts, Thm2 complementarity = gauge-robust Z2 holonomy hol^2 (V38B), Thm3 movable cut. V12 HW (ibm_fez): loop +1, -i excluded ~56sig at ray level; PM 35.4sig over tight bound. "
   "CORRECTION 2026-07-11 (second external audit; row 15->12): (a) the observer object has non-invertible refinement isometries, so it is a CATEGORY with a switch subgroupoid, NOT a groupoid - reworded; (b) paper D still carried stale mu_{4d}/half-tau local-valuation text -> synced to V46 (mu_d even / mu_{2d} odd); (c) movable-cut theorem underformalized (empirical-invariance vs section-phase vs cocycle not separated) -> downgraded pending a commutative-diagram proof; (d) hardware significance restated as shot-noise-only under the witness model, assumption-dependent; (e) Copenhagen/collapse readings marked interpretation conditional on the axioms, not derivations. The earlier 'external pass found no flaws / last point awarded' is SUPERSEDED. Any error found moves the score DOWN - that is the system working."),
]
def show(tag, idx):
    tot=sum(r[idx] for r in ROWS); W=sum(r[1] for r in ROWS)
    print(f"\n{tag}: {tot}/{W}")
    for r in ROWS: print(f"  {r[0]:<42} {r[idx]:>2}/{r[1]}")
    return tot
a=show("AS WRITTEN (Feb 2026 note)",2); b=show("CURRENT (with patches+certificates)",3)
print(f"\nscore: {a} -> {b}   (+/-5 judgment band; was 100 on 2026-07-11, moved to {b} by the second external audit "
      f"(V37/V40 CP-range + counterexample fixes; paper D groupoid->category; hardware caveat) - errors found move it DOWN. "
      f"Core Weyl/AvN obstruction-spectrum program unaffected. 2026-07-12 findings (in KNOWN_LIMITATIONS/NOVELTY): "
      f"hardware combined 80sigma is shot-noise-only (devices fail homogeneity chi2~266/2; systematics-aware ~7sigma; per-device 32-61sigma robust); "
      f"and a directly on-topic uncited paper (Abramsky-Cercelescu-Constantin, FSCD 2024) must be compared to the spectrum result before the flagship is posted.)")
