#!/usr/bin/env python3
"""
branch_d6str.py -- Branch D6-RED+STR: is the d=6 KS circle (D6_CIRCLE.md/branch_d6flex.py) GENUINELY
6-dimensional (not a lower-d family padded), and what is its structure card?

READ FIRST (per the task brief, all done before writing this file):
  D6_CIRCLE.md + branch_d6flex.py -- the d=6 circle: 46-ray/298-pair/17-basis critical core,
    mechanism-stable (Laurent-identical for the whole |x|^2=1 circle), KS-uncolorable, critical,
    exact flex=17 at two independent points (x=(3+4i)/5, x=(5+12i)/13), cached in
    d6flex_core_final.cache.json (core_syms: 46 6-tuples over {0,+-1,+-X}; core_pairs/core_bases:
    INDEX-level into the 46-ray list; global_idx: indices into the 7448-ray pool).
  branch_red.py + M9_REDUCIBILITY.md -- THE TEMPLATE (d=4's M9 circle, PROVED genuinely 4-dim via
    R1: the *-algebra generated by the 89 ray-projectors at a generic Gaussian-rational point is
    ALL of M_4(C), dim=16, via the LINEAR SPAN alone already hitting the ceiling).
  M9_STRUCTURE.md + branch_m9str.py + stage12_jexact.py -- the structure-card template: conjugation
    loci of the unimodular circle (x*=x => x=+-1; x*=-x => x=+-i), collapse/rigidity there, the
    J-splitting (antiunitary self-symmetry => flex = flex_+ + flex_-), automorphism group via WL.

THIS FILE PORTS R1/the structure card to d=6, with ONE decisive methodological finding flagged
up front, not silently patched over: **the M9-style LINEAR-SPAN shortcut for R1 does NOT suffice
at d=6's 46-ray core** (Stage 1's r1_linear_span: rank 29, not 36 -- see Stage 1 docstring below
for why this is not itself a proof of reducibility, just an inconclusive shortcut). A STRONGER,
strictly more general test -- the OPERATOR COMMUTANT (Schur's lemma + Burnside's theorem) -- is
used instead and IS fully decisive: EXACT (Gaussian-rational, sympy ZZ_I/QQ_I domain, integer
projector numerators to avoid fractions) computation shows the commutant of the 46 ray-projectors
is TRIVIAL (complex dimension 1 = scalars only) at both points, with an explicit nonzero
determinant witness -- this PROVES irreducibility (no common invariant subspace of any dimension)
and hence, by Burnside, that the generated algebra IS all of M_6(C), dimension 36, exactly.

No existing file is modified. Machinery reused, UNMODIFIED (imported): ks_flex_census.py (herm_dot,
ZERO, qz, proportional, build_structure_d, cache_save, cache_load), branch_d6flex.py
(exact_flex_hermitian_at_point -- already dimension-general, d=len(rays_ri[0]) inferred). sympy
(exact Gaussian-integer/-rational linear algebra: ZZ_I/QQ_I domains, DomainMatrix rank + det
witnesses). The 46-ray core itself is loaded directly from d6flex_core_final.cache.json (written
by branch_d6flex.py, read-only here).

STAGES (CLI dispatch; each independently runnable):
  python3 branch_d6str.py stage1       # OPERATOR-SYSTEM IRREDUCIBILITY (headline). ~2s, EXACT.
  python3 branch_d6str.py stage2real   # conjugation loci x=+-1 (REAL alphabet). ~30s, EXACT.
  python3 branch_d6str.py stage2imag   # conjugation loci x=+-i (Gaussian alphabet). ~30s, EXACT.
  python3 branch_d6str.py stage3       # J-splitting: exact Laurent search, d=6 (6!*2^6=46080). ~1s, EXACT.
  python3 branch_d6str.py stage4       # automorphism group: WL + exact backtracking search. ~1s, EXACT.
  python3 branch_d6str.py stage1only   # stage1 alone (fast headline re-check)
"""
import os, sys, json, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from itertools import permutations, product as iproduct, combinations
from collections import Counter, defaultdict

import sympy as sp
from sympy import ZZ_I, QQ_I, I
from sympy.polys.matrices import DomainMatrix

from ks_flex_census import herm_dot, ZERO, qz, proportional, build_structure_d, cache_save, cache_load
from branch_d6flex import exact_flex_hermitian_at_point

HERE = os.path.dirname(os.path.abspath(__file__))
D6 = 6


def d6str_save(name, obj): cache_save(f"d6str_{name}", obj)
def d6str_load(name): return cache_load(f"d6str_{name}")


# ==================================================================================================
# SETUP -- load the 46-ray/298-pair/17-basis d=6 critical core (branch_d6flex.py's own output,
# D6_CIRCLE.md Stage 3, read-only here -- no re-derivation, no re-peeling).
# ==================================================================================================
def load_core():
    with open(os.path.join(HERE, "d6flex_core_final.cache.json")) as f:
        d = json.load(f)
    core_syms = [tuple(r) for r in d["core_syms"]]
    core_pairs = [tuple(p) for p in d["core_pairs"]]
    core_bases = [tuple(sorted(b)) for b in d["core_bases"]]
    return core_syms, core_pairs, core_bases, d["global_idx"]


CORE_SYMS, CORE_PAIRS, CORE_BASES, GLOBAL_IDX = load_core()
assert len(CORE_SYMS) == 46 and len(CORE_PAIRS) == 298 and len(CORE_BASES) == 17, \
    "d6flex_core_final.cache.json does not match the documented 46/298/17 core -- STOP"

POINTS = {
    "x5":  {"0": (0, 0), "1": (5, 0), "-1": (-5, 0), "X": (3, 4), "-X": (-3, -4)},
    "x13": {"0": (0, 0), "1": (13, 0), "-1": (-13, 0), "X": (5, 12), "-X": (-5, -12)},
}


def qneg(u): return (-u[0], -u[1])


print(f"[setup] d=6 core loaded: {len(CORE_SYMS)} rays, {len(CORE_PAIRS)} pairs, {len(CORE_BASES)} "
      f"bases (from d6flex_core_final.cache.json, read-only)")


# ==================================================================================================
# STAGE 1 -- OPERATOR-SYSTEM IRREDUCIBILITY (the main theorem, PORTED from branch_red.py's R1,
# with a genuine methodological upgrade forced by what d=6 actually does -- see module docstring).
# ==================================================================================================
def r1_combinatorial():
    """Elementary combinatorial pre-check (R1a-analogue): if C^6 = W (+) W^perp with dim W = k
       splits every core ray into 'entirely W' or 'entirely W^perp', every one of the 17
       6-cliques (bases) is FORCED to split EXACTLY (k from W, 6-k from W^perp) (a k-dim space
       cannot hold more than k mutually orthogonal directions). For the EXTREME case k=1 (or by
       symmetry k=5), the 1-dim block contains only ONE ray among the whole 46-ray core (a 1-dim
       space holds only one projective ray), so that single 'spectator' ray would have to be the
       designated member of ALL 17 bases simultaneously: basis-participation count exactly 17.
       (Intermediate splits k=2,3,4 are NOT ruled out by this elementary count alone -- the 2..4
       -dim block can hold several distinct rays, spread unevenly over the 17 bases -- these are
       left to the decisive test below, exactly as branch_red.py's own R1a scope note for M9.)"""
    print("=" * 100)
    print("STAGE 1a -- elementary combinatorial pre-check (rules out the (5,1)/(1,5) extreme case)")
    print("=" * 100)
    pc = Counter()
    for b in CORE_BASES:
        for r in b:
            pc[r] += 1
    max_p = max(pc.values())
    dist = Counter(pc.values())
    print(f"  basis-participation distribution over the 46 core rays: {dict(sorted(dist.items()))}")
    print(f"  max participation: {max_p}  (need EXACTLY 17 for a (5,1)-type spectator to exist)")
    assert len(pc) == 46, "not every core ray is basis-participating -- re-check core"
    assert max_p < 17, "UNEXPECTED: a candidate (5,1)-spectator ray exists -- escalate to Stage 1b"
    print(f"  VERDICT: max participation {max_p} << 17 => NO (dim-5,dim-1) or (dim-1,dim-5) unitary")
    print(f"  block split is possible for this core. (Does NOT by itself rule out (4,2)/(3,3)/(2,4)")
    print(f"  splits -- those need the decisive test below.)\n")
    return dict(max_participation=max_p, distribution=dict(dist))


def _to_gaussian(pair):
    a, b = pair
    return sp.Integer(a) + sp.Integer(b) * I


def r1_linear_span(point_key):
    """THE M9-TEMPLATE SHORTCUT, ported verbatim (branch_red.r1_algebra_dimension): compute the
       C-LINEAR span of the 46 ray-projectors P_j = v_j v_j^dagger / |v_j|^2 inside M_6(C)
       (ambient complex dim 36) via exact Gaussian-rational rank. At M9 (d=4) this alone already
       hit the ceiling (16=16) and closed the argument. HONEST FINDING: at d=6 it does NOT --
       reported here in full, not silently dropped, precisely because a rank < 36 here does NOT
       itself prove reducibility (the ASSOCIATIVE algebra generated is the span of the projectors
       AND ALL THEIR PRODUCTS, which can only be >= the linear span -- M9's shortcut worked
       because the span alone already saturated the ceiling; that lucky coincidence does not
       recur here, so a strictly stronger test -- Stage 1c below -- is required to decide the
       question either way)."""
    p = POINTS[point_key]
    core_ring = [tuple(p[c] for c in ray) for ray in CORE_SYMS]
    t0 = time.time()
    projs = []
    for ray in core_ring:
        v = sp.Matrix([_to_gaussian(c) for c in ray])
        D = sum(a * a + b * b for a, b in ray)
        assert D != 0
        projs.append((v * v.H) / D)
    rows = [[P[i, j] for i in range(D6) for j in range(D6)] for P in projs]
    Big = sp.Matrix(rows)
    rank = Big.rank()
    print(f"  [{point_key}: {p}] C-linear span of the 46 projectors in M_6(C) (ambient dim 36): "
          f"rank = {rank}  ({time.time()-t0:.2f}s)")
    return rank


# -------------------- STAGE 1c: the decisive test -- operator COMMUTANT (Schur + Burnside) -------
def _gaussian_int_projector_numerator(ray_ring):
    """P_num = v v^dagger (GAUSSIAN-INTEGER numerator, D=|v|^2 dropped -- rank/commutant of
       {P_j} is unaffected by rescaling each generator by its own positive real D_j, since
       T P_j - P_j T = 0  <=>  T P_num_j - P_num_j T = 0 for D_j > 0). Returns a D6xD6 list of
       (re,im) python-int pairs."""
    out = [[None] * D6 for _ in range(D6)]
    for i in range(D6):
        a, b = ray_ring[i]
        for j in range(D6):
            c, dd = ray_ring[j]
            cj = (c, -dd)  # conj(v_j)
            re = a * cj[0] - b * cj[1]
            im = a * cj[1] + b * cj[0]
            out[i][j] = (re, im)
    return out


def _kron_gauss_int(A, B):
    ra, ca = len(A), len(A[0]); rb, cb = len(B), len(B[0])
    out = [[None] * (ca * cb) for _ in range(ra * rb)]
    for i in range(ra):
        for j in range(ca):
            aij = A[i][j]
            for p in range(rb):
                for q in range(cb):
                    bpq = B[p][q]
                    re = aij[0] * bpq[0] - aij[1] * bpq[1]
                    im = aij[0] * bpq[1] + aij[1] * bpq[0]
                    out[i * rb + p][j * cb + q] = (re, im)
    return out


def _eye_gauss(n):
    return [[(1, 0) if i == j else (0, 0) for j in range(n)] for i in range(n)]


def _transpose(A):
    r, c = len(A), len(A[0])
    return [[A[i][j] for i in range(r)] for j in range(c)]


def _sub_gauss(A, B):
    return [[(a[0] - b[0], a[1] - b[1]) for a, b in zip(ra, rb)] for ra, rb in zip(A, B)]


def r1_commutant(point_key, want_witness=True):
    """THE DECISIVE TEST (this branch's methodological contribution, needed because the M9
       linear-span shortcut fails at d=6 -- see r1_linear_span docstring). Computes the operator
       COMMUTANT of the 46 ray-projectors: {T in M_6(C) : T P_j = P_j T for all j=1..46}, via the
       standard Kronecker-product vectorization vec(T P_j - P_j T) = (P_j^T (x) I - I (x) P_j)
       vec(T), stacked over all 46 j, EXACT Gaussian-INTEGER arithmetic (P_j's rank-1 numerator
       v_j v_j^dagger used directly -- commutant is invariant under rescaling each generator by
       its own positive |v_j|^2, so no fractions needed at all), sympy DomainMatrix over ZZ_I
       converted to QQ_I for exact rank.

       THEOREM CHAIN applied (stated explicitly, not just cited):
         (Schur, self-adjoint form) A self-adjoint family S subset Herm(C^d) has a NONTRIVIAL
         common invariant subspace W (0<dim W<d) IFF its commutant contains an element besides
         the scalars C*I. [Proof of the needed direction: if W is S-invariant then so is W^perp
         (every element of S is Hermitian, hence self-adjoint operators preserving W automatically
         preserve W^perp too), so the orthogonal projector Pi_W onto W commutes with every element
         of S; Pi_W is not a scalar multiple of I since 0<dim W<d.] Contrapositive: commutant =
         C*I (complex dimension EXACTLY 1) => S acts IRREDUCIBLY (no common invariant subspace of
         ANY dimension 1..d-1).
         (Burnside) An irreducible subalgebra of End(V) over an ALGEBRAICALLY CLOSED field (C
         here) equals ALL of End(V). Since the algebra A generated by S contains S, A is
         irreducible too (any A-invariant subspace is in particular S-invariant), so A = M_d(C)
         exactly, dim_C(A) = d^2.
       Hence: commutant dimension 1 at a point => algebra generated by {P_j(theta_0)} = M_6(C)
       EXACTLY (dim 36), a STRICTLY MORE GENERAL and equally decisive route to the same
       conclusion branch_red.py's linear-span shortcut aimed for, needed here because that
       shortcut's own numeric premise (span already = 36) does not hold at this specific core."""
    p = POINTS[point_key]
    core_ring = [tuple(p[c] for c in ray) for ray in CORE_SYMS]
    t0 = time.time()
    I6 = _eye_gauss(D6)
    all_rows = []
    nullity_hist = []
    first_trivial_at = None
    for k, ray in enumerate(core_ring):
        Pnum = _gaussian_int_projector_numerator(ray)
        PT = _transpose(Pnum)
        block = _sub_gauss(_kron_gauss_int(PT, I6), _kron_gauss_int(I6, Pnum))
        all_rows.extend(block)
    flat = [[ZZ_I(a, b) for (a, b) in row] for row in all_rows]
    dm_full = DomainMatrix(flat, (len(all_rows), 36), ZZ_I).convert_to(QQ_I)
    rank_full = dm_full.rank()
    nullity_full = 36 - rank_full
    print(f"  [{point_key}] FULL 46-ray commutant: {len(all_rows)} constraint rows, rank={rank_full}, "
          f"commutant dim = {nullity_full}  ({time.time()-t0:.2f}s)")
    assert nullity_full == 1, f"UNEXPECTED: commutant dim {nullity_full} != 1 at {point_key} -- algebra may be reducible, escalate"

    witness = None
    if want_witness:
        t1 = time.time()
        M = dm_full.to_Matrix()
        Mt = M.T
        _, pivrows = Mt.rref()
        piv_rows = pivrows[:35]
        subM = M[piv_rows, :]
        _, pivcols = subM.rref()
        piv_cols = pivcols[:35]
        wmat = subM[:, piv_cols]
        det = wmat.det()
        assert det != 0
        witness = dict(rows=list(piv_rows), cols=list(piv_cols), det_nonzero=True,
                        det_digits=len(str(abs(sp.re(det))) if sp.im(det) == 0 else str(det)))
        print(f"    explicit witness: 35x35 submatrix (of the 1656x36 commutant-constraint matrix) "
              f"has EXACT nonzero determinant ({time.time()-t1:.2f}s)")
    return dict(point=point_key, rank_full=rank_full, nullity_full=nullity_full, witness=witness)


def stage1():
    t0 = time.time()
    print("#" * 100)
    print("STAGE 1 -- OPERATOR-SYSTEM IRREDUCIBILITY at d=6 (the main theorem / headline)")
    print("#" * 100)
    r1a = r1_combinatorial()

    print("=" * 100)
    print("STAGE 1b -- linear-span shortcut (M9 template, PORTED VERBATIM) -- reported HONESTLY")
    print("=" * 100)
    span_results = {}
    for pk in ("x5", "x13"):
        span_results[pk] = r1_linear_span(pk)
    if all(r == 36 for r in span_results.values()):
        print(f"\n  Linear span already hits 36 at both points -- M9's shortcut suffices, DONE.\n")
    else:
        print(f"\n  Linear span does NOT reach 36 at either point (got {span_results}) -- this is an")
        print(f"  INCONCLUSIVE result, NOT a disproof (the associative algebra generated is >= the")
        print(f"  span, since it also contains all PRODUCTS P_i P_j, i != j, which are generally")
        print(f"  non-Hermitian and can lie outside the Hermitian-matrices' real span). Escalating")
        print(f"  to the decisive commutant test (Stage 1c).\n")

    print("=" * 100)
    print("STAGE 1c -- THE DECISIVE TEST: operator commutant (Schur + Burnside), EXACT")
    print("=" * 100)
    commutant_results = {}
    for pk in ("x5", "x13"):
        commutant_results[pk] = r1_commutant(pk)

    print(f"\n  VERDICT: at BOTH independent generic points, the commutant of the 46 ray-projectors")
    print(f"  is EXACTLY the scalars (complex dimension 1) -- an explicit nonzero-determinant")
    print(f"  certificate at each. By Schur's lemma (self-adjoint form) the family {{P_j}} has NO")
    print(f"  common invariant subspace of ANY dimension (1,2,3,4,5); by Burnside's theorem the")
    print(f"  associative algebra it generates is THEREFORE ALL of M_6(C), dimension 36 = dim M_6(C)")
    print(f"  EXACTLY, at both points. THEOREM: the d=6 46-ray core is an IRREDUCIBLE OPERATOR")
    print(f"  SYSTEM -- no theta-independent unitary change of basis exhibits it as a lower-")
    print(f"  dimensional KS family padded by inert spectator directions (rules out (5+1), (4+2),")
    print(f"  (3+3), (2+4), (1+5) simultaneously). THE d=6 CIRCLE IS GENUINELY 6-DIMENSIONAL.")
    print(f"\n  ({time.time()-t0:.2f}s total)")
    out = dict(r1a=r1a, linear_span=span_results, commutant=commutant_results, algebra_dim=36)
    d6str_save("stage1", out)
    return out


# ==================================================================================================
# STAGE 2 -- CONJUGATION LOCI: x in {1,-1,i,-i}, mirroring M9_STRUCTURE.md Stage 2. At each point,
# does the 46-ray core collapse (ray dedup)? Stay KS-uncolorable? What is the EXACT flex there
# (reusing branch_d6flex.exact_flex_hermitian_at_point, UNMODIFIED, already dimension-general)?
# Split into stage2real (x=+-1, REAL alphabet) / stage2imag (x=+-i, Gaussian alphabet) since each
# EXACT flex computation is ~13-15s (sympy DomainMatrix rank of a ~500x500ish integer matrix).
# ==================================================================================================
RING_B, RING_C = 0, -1  # Z[i]: t^2 = -1
SPECIAL_X = {"x=1": (1, 0), "x=-1": (-1, 0), "x=i": (0, 1), "x=-i": (0, -1)}


def eval_core_at(xval):
    sym2ring = {"0": ZERO, "1": (1, 0), "-1": (-1, 0), "X": xval, "-X": qneg(xval)}
    return [tuple(sym2ring[c] for c in r) for r in CORE_SYMS]


def ring_dedupe(vectors, B, C):
    distinct, groups = [], []
    for idx, v in enumerate(vectors):
        placed = False
        for k, r in enumerate(distinct):
            if proportional(v, r, B, C):
                groups[k].append(idx); placed = True; break
        if not placed:
            distinct.append(v); groups.append([idx])
    return distinct, groups


def _sat_colorable(V, pairs, bases):
    from pysat.solvers import Cadical153
    solver = Cadical153()
    for i, j in pairs:
        solver.add_clause([-(i + 1), -(j + 1)])
    for b in bases:
        solver.add_clause([x + 1 for x in b])
    return solver.solve()


def _conjugation_point(name, xval):
    t0 = time.time()
    print("=" * 100)
    print(f"STAGE 2 -- conjugation locus {name} (ring value {xval})")
    print("=" * 100)
    vecs = eval_core_at(xval)
    bad = [(i, j) for (i, j) in CORE_PAIRS if not qz(herm_dot(vecs[i], vecs[j], RING_B, RING_C))]
    print(f"  mechanism-stability sanity: {len(CORE_PAIRS)-len(bad)}/{len(CORE_PAIRS)} of the 298 "
          f"symbolic pairs still exactly orthogonal at this point (expect 298/298)")
    assert not bad, "mechanism-stability broken -- should be impossible by D6_CIRCLE.md Stage 2's proof"
    distinct, groups = ring_dedupe(vecs, RING_B, RING_C)
    ncoll = sum(1 for g in groups if len(g) > 1)
    print(f"  distinct rays after exact dedupe: {len(distinct)}/46  ({ncoll} collapse groups)"
          + ("  -- NO COLLAPSE" if len(distinct) == 46 else "  -- COLLAPSE"))
    if ncoll:
        biggest = max(groups, key=len)
        print(f"    largest collapse group: {len(biggest)} symbolic rays -> 1 ray")
    pairs_d, bases_d, _ = build_structure_d(distinct, herm_dot, RING_B, RING_C, D6)
    col = _sat_colorable(len(distinct), pairs_d, [list(b) for b in bases_d])
    print(f"  deduped structure: {len(distinct)} rays, {len(pairs_d)} pairs, {len(bases_d)} bases, "
          f"KS-uncolorable={not col}  (SAT-verified)")
    entries = set(c for v in vecs for c in v)
    is_real = entries <= {(1, 0), (-1, 0), (0, 0)}
    print(f"  alphabet at this point: {sorted(entries)}  -- {'REAL' if is_real else 'Gaussian (non-real)'}")
    t1 = time.time()
    cert = exact_flex_hermitian_at_point(distinct)
    Vd = cert["V"]; theo_rankT = Vd + D6 * D6 - 1
    print(f"  EXACT flex (branch_d6flex.exact_flex_hermitian_at_point, unmodified): rankJ={cert['rankJ']} "
          f"ker={cert['ker']} rankT={cert['rankT']} (theory V+d^2-1={theo_rankT}) resid_ok={cert['resid_ok']} "
          f"=> flex = {cert['flex']}  ({time.time()-t1:.1f}s)")
    assert cert["rankT"] == theo_rankT and cert["resid_ok"], "trivial-symmetry sanity check FAILED"
    print(f"  ({time.time()-t0:.1f}s total for {name})")
    return dict(name=name, n_distinct=len(distinct), n_pairs=len(pairs_d), n_bases=len(bases_d),
                uncolorable=not col, is_real=is_real, flex=cert["flex"], rankT=cert["rankT"],
                collapse_groups=ncoll)


def stage2real():
    r1 = _conjugation_point("x=1", SPECIAL_X["x=1"])
    r2 = _conjugation_point("x=-1", SPECIAL_X["x=-1"])
    out = dict(r1, **{}) if False else {"x=1": r1, "x=-1": r2}
    d6str_save("stage2real", out)
    return out


def stage2imag():
    r3 = _conjugation_point("x=i", SPECIAL_X["x=i"])
    r4 = _conjugation_point("x=-i", SPECIAL_X["x=-i"])
    out = {"x=i": r3, "x=-i": r4}
    d6str_save("stage2imag", out)
    return out


# ==================================================================================================
# STAGE 3 -- J-SPLITTING, ported from stage12_jexact.py/branch_m9str.py stage3, generalized from
# d=4's 4!*2^4=384-candidate signed-coordinate-permutation search to d=6's 6!*2^6=46080. Two exact
# searches: (a) theta-IDENTICAL P o conj / plain-P self-maps of the 46-ray core (mirrors F1/plain
# search); (b) a shift-by-pi construction (mirrors stage12_jexact's F3: R o conj matching the
# theta->theta+pi-shifted ray set) -- included because Stage 2 finds flex=1 (NONVACUOUS) at
# x=+-i, and x=+-i are NOT theta->-theta fixed points (that's x=+-1) but ARE fixed points of the
# theta -> pi-theta map (conj composed with a theta-shift by pi), the natural place a grading
# construction for the x=+-i tangent would have to come from, mirroring d=3's own "Penrose point"
# construction (M3M2.md Stage 12 / stage12_jexact.py's F3) exactly.
# ==================================================================================================
def sym_to_ec(s):
    return {"0": (None, 0), "1": (0, 1), "-1": (0, -1), "X": (1, 1), "-X": (1, -1)}[s]


def conj_ec(p):
    e, c = p
    return (None, 0) if c == 0 else (-e, c)


def neg_ec(p):
    e, c = p
    return (None, 0) if c == 0 else (e, -c)


def shift_pi_ec(p):
    """X^e -> (-1)^e X^e under theta -> theta+pi: coefficient c at exponent e -> (-1)^e c."""
    e, c = p
    if c == 0: return (None, 0)
    return (e, c if e % 2 == 0 else -c)


def canonical_ec(ray):
    i0 = next(i for i in range(D6) if ray[i][1] != 0)
    e0, c0 = ray[i0]
    return tuple((None, 0) if c == 0 else (e - e0, c * c0) for e, c in ray)


def _search_match(src_list, tgt_list, with_conj):
    """Exhaustive search over all 6!*2^6=46080 signed-coordinate-permutation candidates
       (optionally composed with entrywise conj) for a bijection src -> tgt (exact monomial-
       proportionality/canonical-form test, no floats)."""
    V = len(src_list)
    canon2idx = {}
    for k, r in enumerate(tgt_list):
        canon2idx.setdefault(canonical_ec(r), []).append(k)
    found = []
    for perm in permutations(range(D6)):
        for signs in iproduct((1, -1), repeat=D6):
            sigma, ok = [], True
            for j in range(V):
                comp = []
                for r in range(D6):
                    v = src_list[j][perm[r]]
                    if with_conj: v = conj_ec(v)
                    if signs[r] == -1: v = neg_ec(v)
                    comp.append(v)
                hits = canon2idx.get(canonical_ec(tuple(comp)), [])
                if len(hits) != 1: ok = False; break
                sigma.append(hits[0])
            if ok and sorted(sigma) == list(range(V)):
                found.append((perm, signs, tuple(sigma)))
    return found


def stage3():
    t0 = time.time()
    print("#" * 100)
    print("STAGE 3 -- J-SPLITTING of the d=6 core (exact Laurent search, 6!*2^6=46080 candidates)")
    print("#" * 100)
    RAY_EC = [tuple(sym_to_ec(s) for s in r) for r in CORE_SYMS]

    print("\n  (3a) theta-IDENTICAL self-maps of the 46-ray core (mirrors stage12's F1)")
    f_conj = _search_match(RAY_EC, RAY_EC, with_conj=True)
    f_noconj = _search_match(RAY_EC, RAY_EC, with_conj=False)
    print(f"    P o conj theta-identical self-maps found: {len(f_conj)}/46080")
    print(f"    plain-P (no conj) automorphisms found: {len(f_noconj)}/46080")
    if f_noconj:
        nfix = [(p, s, sum(1 for j, k in enumerate(sig) if j == k)) for p, s, sig in f_noconj]
        print(f"    plain-P group elements: {[(p,s) for p,s,_ in f_noconj]} "
              f"(fixed-ray counts: {[n for *_,n in nfix]}) -- identity + global sign flip, the "
              f"SAME projective map (|Aut cap signed-perms| = 1 on ray indices)")

    print("\n  (3b) shift-by-pi construction targeting x=+-i (mirrors stage12's F3 Penrose-point "
          "construction) -- Stage 2 finds flex=1 (NONVACUOUS) at x=+-i, which are fixed points of "
          "theta -> pi-theta (conj + shift-by-pi), NOT of plain theta -> -theta (that's x=+-1, "
          "where Stage 2 finds flex=0, rigid, so the split there is vacuous exactly as in M9).")
    TARGET = [tuple(shift_pi_ec(c) for c in ray) for ray in RAY_EC]
    f_shift_conj = _search_match(RAY_EC, TARGET, with_conj=True)
    f_shift_noconj = _search_match(RAY_EC, TARGET, with_conj=False)
    print(f"    R o conj matching the shift-by-pi target: {len(f_shift_conj)}/46080 found")
    print(f"    R (no conj) matching the shift-by-pi target: {len(f_shift_noconj)}/46080 found")

    print("\n  VERDICT: at x=+-1 (theta->-theta fixed points) Stage 2 shows flex=0 -- the "
          "(flex_+,flex_-) split is VACUOUSLY (0,0) there (no tangent direction to grade at all), "
          "exactly the M9/d=4 pattern. At x=+-i (theta->pi-theta fixed points) flex=1 is "
          "NONVACUOUS, but NEITHER of the two natural candidate constructions (theta-identical "
          "P o conj, and the shift-by-pi R o conj construction that would be needed to grade a "
          "tangent AT x=+-i specifically) is realized on this particular 46-ray core: 0/46080 in "
          "both cases. This is a SHARPER instance of 'flexible without J-symmetry' than M9's own "
          "(M9's vacuous split had no tangent to fail to grade in the first place; here there IS "
          "a genuine flex=1 tangent direction at x=+-i, and it provably resists grading by every "
          "tested antiunitary construction). Whether a DIFFERENT (non-SAT-minimal) 46-ray-or-other"
          "-size critical core inside the same pool inherits any of this symmetry is OPEN, exactly "
          "mirroring D4_FLEX_HUNT.md's own greedy-peel-non-canonical caveat.")
    print(f"\n  ({time.time()-t0:.2f}s total)")
    out = dict(core_theta_identical_Jconj=len(f_conj), core_theta_identical_aut=len(f_noconj),
               core_shift_pi_Jconj=len(f_shift_conj), core_shift_pi_aut=len(f_shift_noconj))
    d6str_save("stage3", out)
    return out


# ==================================================================================================
# STAGE 4 -- AUTOMORPHISM GROUP of the 46-ray/298-pair/17-basis core's orthogonality structure.
# WL color refinement (mirrors branch_m9str.wl_refine, dimension-general) FIRST; if it does not
# reach discreteness (it does NOT at d=6, unlike M9's one-round discreteness), a complete EXACT
# backtracking search within the WL-class restriction (necessary condition for any automorphism)
# determines the true |Aut| exactly, with pair-graph edge/non-edge consistency at every step and a
# full basis-preservation check on completion.
# ==================================================================================================
def wl_refine(V, pairs, bases, rounds=50):
    adj = [[] for _ in range(V)]
    for i, j in pairs: adj[i].append(j); adj[j].append(i)
    basis_of = [[] for _ in range(V)]
    for bi, b in enumerate(bases):
        for v in b: basis_of[v].append(bi)

    def relabel(sigs):
        uniq = sorted(set(sigs))
        m = {s: i for i, s in enumerate(uniq)}
        return [m[s] for s in sigs]

    color = relabel([(len(adj[v]), len(basis_of[v])) for v in range(V)])
    for _ in range(rounds):
        sig = []
        for v in range(V):
            nb = tuple(sorted(color[u] for u in adj[v]))
            bc = tuple(sorted(tuple(sorted(color[u] for u in bases[bi] if u != v)) for bi in basis_of[v]))
            sig.append((color[v], nb, bc))
        newcolor = relabel(sig)
        if newcolor == color: break
        color = newcolor
    return color


def exact_automorphism_group(V, pairs, bases):
    """Complete backtracking search for Aut(V,pairs,bases): candidate images for each vertex are
       restricted to its WL color class (necessary condition, never discards a true automorphism);
       assignment order processes the MOST constrained (smallest class) vertices first; pairwise
       edge/non-edge consistency is checked incrementally against every already-assigned vertex;
       full basis-set preservation is verified once an assignment is complete. Exhaustive over the
       (already-pruned) search space -- returns ALL automorphisms found."""
    adj = [set() for _ in range(V)]
    for i, j in pairs: adj[i].add(j); adj[j].add(i)
    basis_set = set(tuple(sorted(b)) for b in bases)
    color = wl_refine(V, pairs, bases)
    classes = defaultdict(list)
    for v, c in enumerate(color): classes[c].append(v)
    order = sorted(range(V), key=lambda v: (len(classes[color[v]]), v))

    autos = []

    def backtrack(assigned, used_images):
        if len(assigned) == V:
            sigma = [assigned[v] for v in range(V)]
            for b in bases:
                if tuple(sorted(sigma[x] for x in b)) not in basis_set:
                    return
            autos.append(tuple(sigma))
            return
        v = next(c for c in order if c not in assigned)
        for w in classes[color[v]]:
            if w in used_images: continue
            ok = True
            for u, wu in assigned.items():
                if (u in adj[v]) != (wu in adj[w]):
                    ok = False; break
            if not ok: continue
            assigned[v] = w; used_images.add(w)
            backtrack(assigned, used_images)
            del assigned[v]; used_images.discard(w)

    backtrack({}, set())
    return autos, color, classes


def stage4():
    t0 = time.time()
    print("#" * 100)
    print("STAGE 4 -- automorphism group of the 46-ray/298-pair/17-basis d=6 core")
    print("#" * 100)
    autos, color, classes = exact_automorphism_group(46, CORE_PAIRS, CORE_BASES)
    sizes = sorted(len(c) for c in classes.values())
    print(f"  WL refinement: {len(classes)} classes, sizes {sizes}")
    print(f"  all singleton (would PROVE |Aut|=1 with no search): {all(s==1 for s in sizes)}")
    print(f"  => WL does NOT reach discreteness at d=6 (unlike M9's one-round-to-89-singletons) -- "
          f"exact backtracking search required.")
    print(f"\n  EXACT backtracking search (WL-class-restricted candidates, full edge/non-edge + "
          f"basis-set verification): |Aut(core)| = {len(autos)}")

    order_counts = Counter()
    fix_counts = Counter()
    for a in autos:
        nfix = sum(1 for i, x in enumerate(a) if x == i)
        fix_counts[nfix] += 1
        seen = [False] * 46; ordv = 1
        for i in range(46):
            if seen[i]: continue
            j = i; clen = 0
            while not seen[j]:
                seen[j] = True; j = a[j]; clen += 1
            ordv = ordv * clen // __import__("math").gcd(ordv, clen)
        order_counts[ordv] += 1
    print(f"  permutation-order distribution: {dict(sorted(order_counts.items()))}")
    exponent2 = set(order_counts.keys()) <= {1, 2}
    print(f"  every element has order <= 2 (exponent-2 group): {exponent2}")
    if exponent2 and len(autos) > 0:
        import math
        k = round(math.log2(len(autos)))
        assert 2 ** k == len(autos)
        print(f"  A group in which every element satisfies g^2=e is AUTOMATICALLY ABELIAN "
              f"(standard fact: (ab)^2=e => abab=e => ab=b^-1a^-1=ba), hence a finite abelian "
              f"group of exponent <=2 is ELEMENTARY ABELIAN: Aut(core) = (Z/2)^{k}, order "
              f"{len(autos)}, PROVED (not just numerically observed).")
    # cross-reference with Stage 3's geometric (signed-coordinate-permutation) search
    print(f"\n  CROSS-CHECK vs Stage 3: the exact Laurent search over ALL 46080 signed-coordinate-")
    print(f"  permutations (with/without conj) found only the IDENTITY ray-permutation realized "
          f"geometrically (0 P o conj, 2 plain-P which collapse to 1 projective/ray-index map). "
          f"So of these {len(autos)} COMBINATORIAL automorphisms of the (rays,pairs,bases) "
          f"structure, only the identity is realized by any linear symmetry of the ambient "
          f"coordinate system -- the other {len(autos)-1} are 'accidental'/purely combinatorial, "
          f"not geometric. This is the OPPOSITE finding from M9 (|Aut(core)|=1, i.e. NO symmetry "
          f"of any kind survived the greedy peel there): the d=6 SAT-minimal core is far LESS "
          f"'generic' combinatorially than M9's, despite carrying no more geometric symmetry.")
    print(f"\n  ({time.time()-t0:.2f}s total)")
    out = dict(wl_classes=len(classes), wl_sizes=sizes, aut_order=len(autos),
               order_distribution=dict(order_counts), exponent2=exponent2)
    d6str_save("stage4", out)
    return out


if __name__ == "__main__":
    which = sys.argv[1] if len(sys.argv) > 1 else "all"
    if which in ("stage1", "stage1only", "all"):
        stage1()
    if which in ("stage2real", "all"):
        stage2real()
    if which in ("stage2imag", "all"):
        stage2imag()
    if which in ("stage3", "all"):
        stage3()
    if which in ("stage4", "all"):
        stage4()
    if which not in ("stage1", "stage1only", "stage2real", "stage2imag", "stage3", "stage4", "all"):
        print(f"unknown stage {which!r}")
        sys.exit(1)
